# 多维数组对象

In [38]:
import numpy as np

## 生成ndarray的最简单的方法就是array函数，它可以接受任意的序列对象

In [3]:
data = [6, 7.5, 8, 0, 1]
arr = np.array(data)
arr

array([6. , 7.5, 8. , 0. , 1. ])

嵌套序列，自动转换成为多维数组

In [4]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

除非显示的指定，np.array会推断生成数组的数据类型

In [5]:
arr.dtype

dtype('float64')

In [6]:
arr2.dtype

dtype('int32')

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.empty((2, 3, 4))

array([[[6.23042070e-307, 1.69118108e-306, 2.04722549e-306,
         6.23054972e-307],
        [1.78019761e-306, 9.34608432e-307, 7.56599807e-307,
         8.90104239e-307],
        [1.33511290e-306, 8.90092016e-307, 1.89147745e-307,
         2.22522053e-306]],

       [[6.23059726e-307, 6.23053954e-307, 9.34609790e-307,
         8.45593934e-307],
        [9.34600963e-307, 1.86921143e-306, 6.23061763e-307,
         6.23053954e-307],
        [9.34607074e-307, 9.34601642e-307, 1.42410974e-306,
         5.97819431e-322]]])

arange是python的range的数组版

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## ndarray的数据类型 

数据类型，即dtype

In [12]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [13]:
arr1.dtype

dtype('float64')

In [14]:
arr2.dtype

dtype('int32')

astype转换数据类型

In [15]:
arr = np.array([1, 2, 3, 4, 5])

In [16]:
arr.dtype

dtype('int32')

In [17]:
float_arr = arr.astype(np.float64)

In [18]:
float_arr.dtype

dtype('float64')

In [19]:
arr.dtype

dtype('int32')

注：这里的astype并不会改变源数组的类型，astype会产生一个新值

如果我们把浮点数转换成小数，则小数点后面的部分会被消除

In [20]:
arr = np.array([3.4, 5.7, 2.9])

In [21]:
arr

array([3.4, 5.7, 2.9])

In [22]:
arr.astype(np.int32)  # 不会四舍五入，小数直接消除

array([3, 5, 2])

如果数组里面表示的是数字含义的字符串，也可以用astype将它转换成int类型的数组

In [23]:
numeric_string = np.array(['1.23', '4.67', '3', '-9.6'], dtype=np.string_)
numeric_string

array([b'1.23', b'4.67', b'3', b'-9.6'], dtype='|S4')

In [24]:
numeric_string.astype(np.int32)  # 这里如果有小数转换会出错。

ValueError: invalid literal for int() with base 10: b'1.23'

In [25]:
numeric_string.astype(np.float)

array([ 1.23,  4.67,  3.  , -9.6 ])

astype也可以使用另一个数组的类型

In [27]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .257, .380, .44], dtype=np.float64)
int_array.dtype

dtype('int32')

In [28]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## numpy数组算术 

In [29]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [30]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [31]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

同尺寸数组之间的比较会产生一个布尔值的数组

In [32]:
arr2 = np.array([[0., 4., 1.], [7., 4., 5.]])
arr2

array([[0., 4., 1.],
       [7., 4., 5.]])

In [33]:
arr2 > arr1

array([[False,  True, False],
       [ True,  True,  True]])

## 基础索引与切片

In [36]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr[5]

5

In [39]:
arr[5: 8]

array([5, 6, 7])

In [40]:
arr[5:8]=12

In [41]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [42]:
arr_slice = arr[5:8]

In [43]:
arr_slice

array([12, 12, 12])

In [44]:
arr_slice[1] = 33

In [45]:
arr

array([ 0,  1,  2,  3,  4, 12, 33, 12,  8,  9])

In [46]:
arr_slice[:] = 0

In [47]:
arr

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

表明切片的切片也会影响源数组

In [49]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr2d[2]

array([7, 8, 9])

In [51]:
arr2d[2][2]

9

In [53]:
arr2d[2, 2]

9

在二维数组中我们可以将第一个[]看作行，第二个[]看作列

In [55]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [56]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
old_value = arr3d[0].copy()
arr3d[0] = 66
arr3d

array([[[66, 66, 66],
        [66, 66, 66]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [59]:
arr3d[0] = old_value
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### 数组的切片索引

In [60]:
arr

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

In [63]:
arr[5:8]

array([0, 0, 0])

In [65]:
arr[5:8] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [66]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

对于二维的数组，切片有一点不同

In [67]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
arr2d[:2]  # 现在是沿着轴0进行切片  注：对于二维数组 轴0是行，轴1是列

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
arr2d[:3]  # 可以看出，切片起始位置为1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

多组切片

In [70]:
arr2d[:, :1]  # 所有的行，切下第一列

array([[1],
       [4],
       [7]])

索引和切片的混合

In [71]:
arr2d[1, :2]  # 选择第二行，第1，2个数

array([4, 5])

In [72]:
arr2d[:2, 2]  # 切片 先选择前两行，索引 选择第三列

array([3, 6])

更高维度的切片

In [73]:
arr2d[:, :1]  # 选择所有行，第一列

array([[1],
       [4],
       [7]])

当我们对切片表达式赋值时，整个切片会被重新赋值

In [74]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## 布尔索引

In [80]:
names = np.array(['Bob', 'Joe', 'Will', 'Joe', 'Joe', 'RocZhang', 'RocZhang'])
data = np.random.randn(7, 4)

In [81]:
names

array(['Bob', 'Joe', 'Will', 'Joe', 'Joe', 'RocZhang', 'RocZhang'],
      dtype='<U8')

In [82]:
data

array([[ 0.72980409, -0.49117469, -0.95673965, -0.48333672],
       [-0.51954463,  1.07433008, -0.89962895, -0.97595148],
       [ 0.37307097,  1.23244495, -0.46958169,  0.61084689],
       [-0.39761801, -1.69762753,  1.34915577, -1.2724182 ],
       [-0.09348911,  0.6818883 , -0.44788855,  0.46145847],
       [-0.3631995 ,  0.82768341,  1.06220663, -0.00618129],
       [ 0.36978505, -0.27806746, -0.38933291,  0.36907209]])

In [83]:
names == 'Bob'

array([ True, False, False, False, False, False, False])

In [84]:
data[names == 'Bob']  # 这里的data行数与array的个数相同，为True的行显示

array([[ 0.72980409, -0.49117469, -0.95673965, -0.48333672]])

In [85]:
data[names == 'RocZhang', 2:]  # 匹配RocZhang索引的行，显示第二行之后的数

array([[ 1.06220663, -0.00618129],
       [-0.38933291,  0.36907209]])

In [86]:
data[names == 'RocZhang', 3]  # 第二个参数3为索引，3表示第四列

array([-0.00618129,  0.36907209])

In [87]:
names != 'RocZhang'

array([ True,  True,  True,  True,  True, False, False])

In [88]:
data[~(names == 'Bob')]

array([[-0.51954463,  1.07433008, -0.89962895, -0.97595148],
       [ 0.37307097,  1.23244495, -0.46958169,  0.61084689],
       [-0.39761801, -1.69762753,  1.34915577, -1.2724182 ],
       [-0.09348911,  0.6818883 , -0.44788855,  0.46145847],
       [-0.3631995 ,  0.82768341,  1.06220663, -0.00618129],
       [ 0.36978505, -0.27806746, -0.38933291,  0.36907209]])

In [89]:
cond = names == 'Bob'  # names == 'Bob' 会返回一个布尔值的数组
ata[~cond]

array([[-0.51954463,  1.07433008, -0.89962895, -0.97595148],
       [ 0.37307097,  1.23244495, -0.46958169,  0.61084689],
       [-0.39761801, -1.69762753,  1.34915577, -1.2724182 ],
       [-0.09348911,  0.6818883 , -0.44788855,  0.46145847],
       [-0.3631995 ,  0.82768341,  1.06220663, -0.00618129],
       [ 0.36978505, -0.27806746, -0.38933291,  0.36907209]])

In [91]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True, False, False, False, False])

In [92]:
data[mask]

array([[ 0.72980409, -0.49117469, -0.95673965, -0.48333672],
       [ 0.37307097,  1.23244495, -0.46958169,  0.61084689]])

In [93]:
data[data<0]

array([-0.49117469, -0.95673965, -0.48333672, -0.51954463, -0.89962895,
       -0.97595148, -0.46958169, -0.39761801, -1.69762753, -1.2724182 ,
       -0.09348911, -0.44788855, -0.3631995 , -0.00618129, -0.27806746,
       -0.38933291])

将data中小于零的数变为零

In [94]:
data[data<0]=0

In [95]:
data

array([[0.72980409, 0.        , 0.        , 0.        ],
       [0.        , 1.07433008, 0.        , 0.        ],
       [0.37307097, 1.23244495, 0.        , 0.61084689],
       [0.        , 0.        , 1.34915577, 0.        ],
       [0.        , 0.6818883 , 0.        , 0.46145847],
       [0.        , 0.82768341, 1.06220663, 0.        ],
       [0.36978505, 0.        , 0.        , 0.36907209]])

In [96]:
data[names != 'Joe'] = 7

In [97]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.07433008, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 1.34915577, 0.        ],
       [0.        , 0.6818883 , 0.        , 0.46145847],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ]])

In [98]:
names

array(['Bob', 'Joe', 'Will', 'Joe', 'Joe', 'RocZhang', 'RocZhang'],
      dtype='<U8')

## 神奇的索引

In [101]:
arr = np.empty((8, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [102]:
for i in range(8):
    arr[i] = i

In [103]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [104]:
arr[[4, 3, 0, 6]]  # 这里是索引的例子

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [105]:
arr[[-3, -5]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.]])

如果索引中有两个数组是怎么样的

In [106]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [107]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]  # 元素（1， 0），（5， 3）被选中

array([ 4, 23, 29, 10])

## 数组的转置和换轴

In [108]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [109]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [111]:
arr = np.random.randn(6, 3)
arr

array([[-0.18173393, -1.50911602,  0.31414063],
       [-0.82569616, -0.04879588, -0.04225875],
       [ 0.20873119,  1.33050126,  2.14928023],
       [ 0.20565558,  0.74999453, -1.60731439],
       [-2.06234341, -0.80177237,  0.03963943],
       [-0.28535958,  1.33529788,  0.0714973 ]])

In [112]:
np.dot(arr.T, arr)  # 举证的内积

array([[ 5.13535471e+00,  2.01899574e+00, -6.28101418e-03],
       [ 2.01899574e+00,  7.03839696e+00,  1.24581886e+00],
       [-6.28101418e-03,  1.24581886e+00,  7.31001834e+00]])

In [113]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [114]:
arr.transpose((1, 0, 2))  

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [115]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [116]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])