In [3]:
import numpy as np

快速的逐元素数组函数

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.sqrt(arr)  # sqrt() 以元素为单位返回数组的非负平方根。

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
np.exp(arr)  #sqrt() 计算输入数组中所有元素的指数。exp(2)计算e的平方

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

二元通用函数

In [9]:
x = np.random.randn(8)
y = np.random.randn(8)
x

array([ 0.9988955 , -0.58405038, -1.27608013, -0.95406323, -0.48851566,
        0.34528719, -1.23118255,  0.99743269])

In [10]:
y

array([-1.48976925,  0.25066135,  0.93544384,  2.25620383, -0.45630019,
       -1.1978731 ,  0.65225106,  0.76567107])

In [11]:
np.maximum(x, y)  # 选出xy中相应的相对较大的数

array([ 0.9988955 ,  0.25066135,  0.93544384,  2.25620383, -0.45630019,
        0.34528719,  0.65225106,  0.99743269])

In [12]:
arr = np.random.randn(7) * 5
arr

array([ 1.79050012, -5.49889042,  1.11386982,  3.05125428,  3.85177424,
        0.78385282,  2.69468285])

In [13]:
remainder, whole_part = np.modf(arr)  # 按元素返回数组的小数和整数部分。

In [14]:
remainder

array([ 0.79050012, -0.49889042,  0.11386982,  0.05125428,  0.85177424,
        0.78385282,  0.69468285])

In [15]:
whole_part

array([ 1., -5.,  1.,  3.,  3.,  0.,  2.])

通用函数接受一个可选参数out，允许对数组按位置操作

In [16]:
arr

array([ 1.79050012, -5.49889042,  1.11386982,  3.05125428,  3.85177424,
        0.78385282,  2.69468285])

In [17]:
np.sqrt(arr)

D:\software\software\Anaconda\envs\dataAnalysis\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([1.33809571,        nan, 1.05540031, 1.74678398, 1.96259375,
       0.88535463, 1.64154892])

In [19]:
np.sqrt(arr, arr)

D:\software\software\Anaconda\envs\dataAnalysis\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([1.33809571,        nan, 1.05540031, 1.74678398, 1.96259375,
       0.88535463, 1.64154892])

In [20]:
arr

array([1.33809571,        nan, 1.05540031, 1.74678398, 1.96259375,
       0.88535463, 1.64154892])