In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 24.9 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list] 

Wall time: 958 ms


numpy的核心就是N-维的数组对象--ndarray。

In [5]:
data = np.random.randn(2, 3)  # 两行三列
data

array([[-1.26163138, -1.05235363,  0.03917763],
       [-1.52994849, -1.42370946,  0.07052525]])

In [7]:
data * 10 

array([[-12.61631377, -10.5235363 ,   0.39177633],
       [-15.29948492, -14.23709455,   0.70525247]])

In [8]:
data + data

array([[-2.52326275, -2.10470726,  0.07835527],
       [-3.05989698, -2.84741891,  0.14105049]])

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')