In [3]:
import numpy as np

In [4]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [5]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [6]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [7]:
x.dot(y)  # 等价于np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])